import { MD3LightTheme, configureFonts } from 'react-native-paper';
import type { MD3Type } from 'react-native-paper/lib/typescript/types';

const fontConfig: { [key: string]: MD3Type } = {
  displayLarge: {
    fontFamily: 'System',
    fontSize: 57,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'System',
    fontSize: 45,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontSize: 32,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontSize: 28,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'System',
    fontSize: 22,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '500' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'System',
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '400' as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#006A60',
    onPrimary: '#FFFFFF',
    primaryContainer: '#74F8E5',
    onPrimaryContainer: '#00201C',
    secondary: '#4A635F',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#CCE8E2',
    onSecondaryContainer: '#05201C',
    tertiary: '#456179',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#CCE5FF',
    onTertiaryContainer: '#001E31',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#FAFDFC',
    onBackground: '#191C1B',
    surface: '#FAFDFC',
    onSurface: '#191C1B',
    surfaceVariant: '#DAE5E2',
    onSurfaceVariant: '#3F4947',
    outline: '#6F7977',
    outlineVariant: '#BEC9C6',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2E3130',
    inverseOnSurface: '#EFF1F0',
    inversePrimary: '#54DBC9',
    elevation: {
      level0: 'transparent',
      level1: '#F2FAF8',
      level2: '#EDF8F6',
      level3: '#E7F6F3',
      level4: '#E5F5F2',
      level5: '#E2F3F0',
    },
  },
  fonts: configureFonts({ config: fontConfig }),
  roundness: 2,
  animation: {
    scale: 1.0,
  },
} as const;

export type AppTheme = typeof theme; 